version: "3.8"
services:
  worker:
    build: .
    environment: 
      MONGO_URL: "mongodb://mongo:27017/monotone"
      TOKEN: "<Discord Bot Token Here>"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
